repository: Search-GoGo/Search-GoGo
repository_url: https://github.com/WangXxiaoDong/Search-GoGo

timezone: Asia/Shanghai
lang: zh_CN

title: Search-GoGo
alias_en: Search-GoGo
alias_cn: Search-GoGo
description: A Navigation Website
keywords: Search-GoGo, Navigation
url: https://searchgogo.cc
established_at: "2019-02-24T00:00+08:00"

author: WangXxiaoDong
author_url: https://github.com/WangXxiaoDong

image: /images/logo.png
logo: /images/logo.png
logo_dark: /images/logo-dark.svg
logo_white: /images/logo-white.svg

plugins:
- jekyll-seo-tag
- jekyll-sitemap

exclude:
- .gitignore
- .travis.yml
- LICENSE
- README.md
- CNAME
- Gemfile
- Gemfile.lock
- script
- vendor